### PR TITLE
Improve PHP 8.1 compatiblity

### PR DESCRIPTION
**Pull request by sstok**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tickets       | 
| License       | MIT

This drops support for PHP 7 and requires PHP 8.1 at minium.

### CODE REVIEW

**Comment by sstok** [comment]
Hello, actions? Could you kindly run...

**Comment by sstok** [comment]
Ha `$default-branch` doesn't work... we have been lied to!

**Comment by sstok** [comment]
WHY? Why;

WHY is GitHub workflows not working as it should.
WHY is Composer complaining about Symfony Flex while the plug-in is allowed to run, and has no problems locally.

WHY CAN'T I JUST FOR ONCE, FOCUS ON PROGRAMMING RATHER DEALING WITH THIS NONSENSE?!
Three years short on my 20 years anniversary of working with PHP. And yet still, I'm almost no further than I was 10 years ago, not in my career, nor in my life.

I'm finding it harder and harder to justify my suffering and pain, not for a greater purpose, not for a better life or even better problems. No, this perpetual suffering has no purpose. My whole life hasn't been nothing but a pain, from the day I was born onto this planet. Everything I have tried to build-up, only to watch it crumble at the slightest moment! And these last two years have been the worst, rising higher only to fall even deeper than ever before. And then try again.

I love a good challenge, to behold success in the face of failure. But this... what happened these past two years? No... not anymore. There is no God, only pain and the believe it all has some greater purpose.

**Comment by sstok** [comment]
I'm not giving-up on this pr just yet. BUT YOU BETTER WORK NOW GitHub workflow! BECAUSE I'M NOT KIDDING HERE, I furiously angry!!

**Comment by sstok** [comment]
Edit: In case anyone saw my recent comments, and wonders what the hell is going on. I'm gonna keep it short: I'm mentally burned-out, and it's effecting me physically as well.

**Comment by acrobat** [comment]
Thanks 🙌

**Pull request merged**
